### ISSUE TITLE
raise error, v # invalid expression

### ISSUE THREAD

**Issue by wvdongen** [swisskyrepo/Vulny-Code-Static-Analysis#1]
Hi,

Good job on this script. Ran into the following error on Kali 2018.2:

Traceback (most recent call last):
  File "index.py", line 36, in <module>
    recursive(results.dir,0)
  File "/root/Vulny-Code-Static-Analysis/detection.py", line 103, in recursive
    recursive(dir+"/"+name, progress)
  File "/root/Vulny-Code-Static-Analysis/detection.py", line 103, in recursive
    recursive(dir+"/"+name, progress)
  File "/root/Vulny-Code-Static-Analysis/detection.py", line 103, in recursive
    recursive(dir+"/"+name, progress)
  File "/root/Vulny-Code-Static-Analysis/detection.py", line 103, in recursive
    recursive(dir+"/"+name, progress)
  File "/root/Vulny-Code-Static-Analysis/detection.py", line 101, in recursive
    analysis(dir+"/"+name)
  File "/root/Vulny-Code-Static-Analysis/detection.py", line 72, in analysis
    false_positive, declaration_text, line_declaration = check_declaration(content, vulnerable_var[1], path)
  File "/root/Vulny-Code-Static-Analysis/functions.py", line 116, in check_declaration
    return check_declaration(content, "$"+declaration2[0][0], path)
  File "/root/Vulny-Code-Static-Analysis/functions.py", line 113, in check_declaration
    regex_declaration2 = re.compile("\$(.*?)([\t ]*)as(?!=)([\t ]*)\$"+vuln[1:])
  File "/usr/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
sre_constants.error: unbalanced parenthesis

**Comment by wvdongen** [comment]
Added a try except to line 113 in functions.py to get it working.


```
    try:
        regex_declaration2 = re.compile("\$(.*?)([\t ]*)as(?!=)([\t ]*)\$"+vuln[1:])
    except Exception as e:
        return (False, "","")
```

**Comment by tanaydin** [comment]
This is fixed by https://github.com/swisskyrepo/Vulny-Code-Static-Analysis/pull/3
